on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  DISPLAY: '0:0'

jobs:
  linuxs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        build-type: [RelWithDebInfo]
        compiler: [gcc, clang]

    steps:
      - name: Install ROS
        uses: jrl-umi3218/github-actions/install-dependencies@master
        with:
          ros: |
            apt: ros-base
      - name: Install dependencies
        uses: jrl-umi3218/github-actions/install-dependencies@master
        with:
          ubuntu: |
            apt: f2c libopencv-dev libf2c2 libf2c2-dev doxygen cmake libeigen3-dev libjpeg-dev jython libatlas-base-dev libboost-all-dev libpng-dev omniorb

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Build project
        uses: jrl-umi3218/github-actions/build-cmake-project@master
        with:
          compiler: ${{ matrix.compiler }}
          build-type: ${{ matrix.build-type }}


      # - name: Run test
      #   shell: bash
      #   run: |
      #     set -x
      #     export ROS_DISTRO=${{ matrix.ROS_DISTRO }}
      #     ls -al
      #     . ./.travis.sh
