on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  DISPLAY: '0:0'

jobs:
  linuxs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Install ROS
        uses: jrl-umi3218/github-actions/install-dependencies@master
        with:
          ros: |
            apt: ros-base

      - name: Checkout project
        uses: actions/checkout@v4


      # - name: Run test
      #   shell: bash
      #   run: |
      #     set -x
      #     export ROS_DISTRO=${{ matrix.ROS_DISTRO }}
      #     ls -al
      #     . ./.travis.sh
