name: Package openhrp3
on:
  repository_dispatch:
    types:
    - package-master
  push:
    branches:
    - "**"
jobs:
  package:
    uses: jrl-umi3218/github-actions/.github/workflows/package-project.yml@master
    with:
      update-stable-and-head: true
      # deps: '["gergondet/hrpsys-base"]' # TODO reset this when hrpsys-base CI will be fixed
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
